server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_demo
    username: root
    password: emberes1617.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      authorization server:
        issuer: http://localhost:8080
